version: '3.5'

services:
  postgres:
    image: postgres:15.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - teasr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build: 
      context: "."
      dockerfile: Dockerfile
    command: ["node", "/app/dist/server.js"]
    restart: always
    ports:
      - 4001:4000
    networks:
      - teasr-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - PROVIDER_URL=https://rpc-mumbai.maticvigil.com
      - LENS_HUB_CONTRACT_ADDRESS=0x60Ae865ee4C725cd04353b5AAb364553f56ceF82
      - NETWORK=mumbai

networks:
  teasr-network:
    driver: bridge
